language: python
sudo: false
python: 3.6
script: make test
deploy:
  - provider: pypi
    user: titan_550
    password:
      secure: ciw+Y0xRfAGXlE6NdRN+16ZLlh1Cu1l34/Jzhj8vkc24bwc83FgKxWx+O/kVcd2RiHOJVUP4NCHi0EqM8egm6QoXb1Wjxt2xjcx6ipoBgI+mFwa+JNBc2FU1l159X+1a/n9lGhly1eoG7hwfIljrpNfqg7ZIP7lRyGdjtJTheAO7JIqbvBo96h8RzJO5VDHYaqky4mjHQwDE+90ecWb9gITcMtLc9PlXiyNS7aKP00mgSjYIpe3S2wjBoSD2cboKVrKaVdheBxcmh2GSdTvcV2Ykg8HQRXUB3wZZYc9XcmMeRQyELaA3AaCu3aSlTJeC0uKGQI+msAKCttQKyu7tDbCpzNWhu9IeGo2dQ0Tb7gkZY4GudsbRLmMxpz2LLKh9yn9c4cDu5VqfI9MyXtfKvuurunwbJ+vWEzHanFminCjb0Lv15GT9//EGXIlYFiGppmLNwtJjcozuYhGm3tMDZQVFQvBALzPlDumj+sYHxkrJoTxezq8uNfRBPcK89xijdbmjISshnhJgOkUxLb8+OwF+s6WZIStvqPjGMaJZRHCVwNV9mfYgkEe031c5TUrAjWhqfFosvcGf6R7a+iXctFCYWKl7J2ZVmrroo8UTy/45GvHWmMXmlSmaSBoc2P2I0BNTxSyXAPs1MIT6CYF7qPkcyPbYFLR04yNiyoKqiNs=
    on:
      branch: master
      tags: true
  - provider: pypi
    user: titan_550
    password:
      secure: Ywtu7jajCO1/XPWBg1usKNVnFuzPVnRRKg7MvP/oHRUbcnrFA5b0RGhhuE3OoXesngXEOCXY+S/pUC6Iyaw05oi6l1JUd9HmrdfLE68E+WQgBXMzjtIv4NaXcmWTHlRjgjYhJPmMXdza55CwjqXK3zuidtV1VysKoiWNzPR4jBFP8Y2wsx9ucIvfDMBOYlLkqUp15/ZomG26XWv5Cq0Q+4kD6sAAGZBYAZsZ2O6kKVziRK+/0vca1BrE0IrunaPVJcvvNQxwxavaXlcO/ZUn/VAYZWXts1/VaWw10W2viGU5QwHb0yQCCPJYREpxidIP2dBbPn+5ZyRVJEtJGxTzS2VLW+RNXEG/UUNqtGFjN4U7MP57EF9MewOkWPhTMuJ96j8zlfzjh4/2Xc24gPqK7QJSzwDxjoPVqUqyJj+Chcm2UJ6jC0YDaVUGIvDk/m0MNEPLaYvEb0HT8L5U9K5MtDJ5OUcKI2J5dmJcJkgNrFfwFpp5uAAr5uhIlAV6pzmFvca4h65of6aKskQ20vIWumlhuyCdXeUuql5MVzVy7X9Iv4nGbS3XSx2NJohDiJFHXgrW2GiCW+UwQ+HISntNYYEP2qMx6MinjsQL2lm0SZbXVlvNwt5hc8inT005WARiSE4UV7+1/Sb3tmfLk6LaS24tVpS24RtcbRmRINrWnA8=
    server: https://test.pypi.org/legacy/
    on:
      branch: staging